import React, { createContext, useContext, useState } from 'react';

const translations = {
  fr: {
    // Nav
    accueil: 'Accueil',
    guichet: 'Guichet',
    suivi: 'Suivi',
    rendezvous: 'Rendez-vous',
    assistant: 'Assistant IA',
    connexion: 'Connexion',
    inscrire: "S'inscrire",
    deconnexion: 'Déconnexion',
    // Home
    hero_title: 'Simplifiez vos démarches administratives',
    hero_sub: 'Obtenez vos documents officiels en ligne rapidement et en toute sécurité',
    commencer: 'Commencer la demande',
    bureaux: 'Bureaux',
    // Auth
    email: 'Email',
    password: 'Mot de passe',
    nom_complet: 'Nom Complet',
    confirm_pass: 'Confirmer le mot de passe',
    se_connecter: 'Se connecter',
    creer_compte: 'Créer un compte',
    pas_compte: 'Pas de compte ?',
    deja_compte: 'Déjà un compte ?',
    // Forms
    prenom: 'Prénom',
    nom: 'Nom',
    date_naissance: 'Date de naissance',
    lieu_naissance: 'Lieu de naissance',
    cin: 'Numéro CIN',
    sexe: 'Sexe',
    homme: 'Homme',
    femme: 'Femme',
    adresse: 'Adresse complète',
    quartier: 'Quartier',
    ville: 'Ville',
    telephone: 'Téléphone',
    motif: 'Motif',
    profession: 'Profession',
    organisme: 'Organisme',
    pere: 'Nom du père',
    mere: 'Nom de la mère',
    etat_civil: 'État civil',
    celibataire: 'Célibataire',
    retrait: 'Retrait à la commune',
    livraison: 'Livraison à domicile',
    envoyer: 'Envoyer la demande',
    suivant: 'Suivant',
    nb_copies: 'Nombre de copies',
    copie_integrale: 'Copie intégrale',
    extrait: 'Extrait',
    code_postal: 'Code postal',
    // Documents
    acte_naissance: 'Acte de Naissance',
    cert_residence: 'Certificat de Résidence',
    cert_vie: 'Certificat de Vie',
    cert_celibat: 'Certificat de Célibat',
    // Sections
    info_personne: 'Informations sur la personne',
    info_residence: 'Informations sur la résidence',
    info_demande: 'Informations sur la demande',
    info_supplementaires: 'Informations supplémentaires',
    info_admin: 'Informations administratives',
    info_parents: 'Informations sur les parents',
    situation_familiale: 'Situation familiale',
    info_personnelles: 'Informations personnelles',
    // Chat
    chat_title: 'Assistant Watiqa',
    chat_online: 'En ligne',
    chat_welcome: 'Bonjour ! 👋\nJe suis votre assistant Watiqa, spécialisé dans les services administratifs marocains.\n\nPosez-moi vos questions sur :\n🏠 Demandes de documents (certificat de résidence, etc.)\n📋 Procédures administratives\n🏛️ Services communaux\n📅 Rendez-vous et suivi de dossiers\n\nComment puis-je vous aider aujourd\'hui ?',
    chat_placeholder: 'Tapez votre message ici...',
    nouvelle_conv: 'Nouvelle conversation',
    // Suivi
    suivi_title: 'Suivi de vos demandes',
    num_demande: 'Numéro de demande',
    statut: 'Statut',
    date: 'Date',
    en_cours: 'En cours',
    validee: 'Validée',
    prete: 'Prête',
    // Footer
    droits: 'Tous droits réservés',
    contact: 'Contact',
    a_propos: 'À propos',
    besoin_aide: 'Besoin d\'aide?',
    // Guichet
    guichet_title: 'Guichet de Services',
    guichet_sub: 'Choisissez le document que vous souhaitez demander',
    // Steps
    informations: 'Informations',
    confirmation: 'Confirmation',
    termine: 'Terminé',
    demande_envoyee: 'Demande envoyée avec succès !',
    demande_ref: 'Référence de votre demande',
    retour_accueil: "Retour à l'accueil",
    nouvelle_demande: 'Nouvelle demande',
    // RDV
    rdv_title: 'Prendre un Rendez-vous',
    rdv_sub: 'Choisissez un créneau disponible pour votre rendez-vous en commune',
    choisir_commune: 'Choisir une commune',
    choisir_date: 'Choisir une date',
    choisir_heure: 'Choisir un créneau',
    confirmer_rdv: 'Confirmer le rendez-vous',
    objet_rdv: 'Objet du rendez-vous',
    // Admin
    admin_dashboard: 'Tableau de bord',
    admin_demandes: 'Demandes',
    admin_users: 'Utilisateurs',
    admin_logout: 'Quitter l\'Admin',
    stats_demandes: 'Total Demandes',
    stats_users: 'Utilisateurs Inscrits',
    valider: 'Valider',
    refuser: 'Refuser',
    prete_retrait: 'Prête pour retrait',
    aucune_demande: 'Aucune demande',
    aucun_utilisateur: 'Aucun utilisateur',
    role_user: 'Citoyen',
    role_admin: 'Administrateur',
    changer_role: 'Changer Rôle',
    aller_admin: 'Espace Admin',
    retour_citoyen: 'Retour Citoyen',
  },
  ar: {
    accueil: 'الرئيسية',
    guichet: 'الشباك',
    suivi: 'المتابعة',
    rendezvous: 'موعد',
    assistant: 'المساعد الذكي',
    connexion: 'تسجيل الدخول',
    inscrire: 'إنشاء حساب',
    deconnexion: 'تسجيل الخروج',
    hero_title: 'بسّط إجراءاتك الإدارية',
    hero_sub: 'احصل على وثائقك الرسمية عبر الإنترنت بسرعة وأمان',
    commencer: 'ابدأ الطلب',
    bureaux: 'المكاتب',
    email: 'البريد الإلكتروني',
    password: 'كلمة المرور',
    nom_complet: 'الاسم الكامل',
    confirm_pass: 'تأكيد كلمة المرور',
    se_connecter: 'تسجيل الدخول',
    creer_compte: 'إنشاء حساب',
    pas_compte: 'ليس لديك حساب؟',
    deja_compte: 'لديك حساب بالفعل؟',
    prenom: 'الاسم الأول',
    nom: 'اللقب',
    date_naissance: 'تاريخ الميلاد',
    lieu_naissance: 'مكان الميلاد',
    cin: 'رقم بطاقة التعريف',
    sexe: 'الجنس',
    homme: 'ذكر',
    femme: 'أنثى',
    adresse: 'العنوان الكامل',
    quartier: 'الحي',
    ville: 'المدينة',
    telephone: 'الهاتف',
    motif: 'السبب',
    profession: 'المهنة',
    organisme: 'الجهة',
    pere: 'اسم الأب',
    mere: 'اسم الأم',
    etat_civil: 'الحالة المدنية',
    celibataire: 'أعزب',
    retrait: 'الاستلام من البلدية',
    livraison: 'التوصيل إلى المنزل',
    envoyer: 'إرسال الطلب',
    suivant: 'التالي',
    nb_copies: 'عدد النسخ',
    copie_integrale: 'نسخة كاملة',
    extrait: 'مستخرج',
    code_postal: 'الرمز البريدي',
    acte_naissance: 'عقد الازدياد',
    cert_residence: 'شهادة السكنى',
    cert_vie: 'شهادة الحياة',
    cert_celibat: 'شهادة العزوبية',
    info_personne: 'معلومات الشخص',
    info_residence: 'معلومات السكن',
    info_demande: 'معلومات الطلب',
    info_supplementaires: 'معلومات إضافية',
    info_admin: 'معلومات إدارية',
    info_parents: 'معلومات الوالدين',
    situation_familiale: 'الوضع العائلي',
    info_personnelles: 'معلومات شخصية',
    chat_title: 'مساعد وثيقة',
    chat_online: 'متصل',
    chat_welcome: 'مرحباً! 👋\nأنا مساعد وثيقة، متخصص في الخدمات الإدارية المغربية.\n\nيمكنني مساعدتك في:\n🏠 طلبات الوثائق (شهادة السكنى، إلخ)\n📋 الإجراءات الإدارية\n🏛️ الخدمات البلدية\n📅 المواعيد ومتابعة الملفات\n\nكيف يمكنني مساعدتك اليوم؟',
    chat_placeholder: 'اكتب رسالتك هنا...',
    nouvelle_conv: 'محادثة جديدة',
    suivi_title: 'متابعة طلباتكم',
    num_demande: 'رقم الطلب',
    statut: 'الحالة',
    date: 'التاريخ',
    en_cours: 'قيد المعالجة',
    validee: 'تمت المصادقة',
    prete: 'جاهزة',
    droits: 'جميع الحقوق محفوظة',
    contact: 'اتصل بنا',
    a_propos: 'حول',
    besoin_aide: 'تحتاج مساعدة؟',
    guichet_title: 'شباك الخدمات',
    guichet_sub: 'اختر الوثيقة التي تريد طلبها',
    informations: 'المعلومات',
    confirmation: 'التأكيد',
    termine: 'منتهي',
    demande_envoyee: 'تم إرسال الطلب بنجاح!',
    demande_ref: 'مرجع طلبك',
    retour_accueil: 'العودة إلى الرئيسية',
    nouvelle_demande: 'طلب جديد',
    rdv_title: 'أخذ موعد',
    rdv_sub: 'اختر وقتاً متاحاً لموعدك في البلدية',
    choisir_commune: 'اختر البلدية',
    choisir_date: 'اختر التاريخ',
    choisir_heure: 'اختر الوقت',
    confirmer_rdv: 'تأكيد الموعد',
    objet_rdv: 'موضوع الموعد',
    admin_dashboard: 'لوحة القيادة',
    admin_demandes: 'الطلبات',
    admin_users: 'المستخدمون',
    admin_logout: 'الخروج من الإدارة',
    stats_demandes: 'إجمالي الطلبات',
    stats_users: 'المستخدمون المسجلون',
    valider: 'قبول',
    refuser: 'رفض',
    prete_retrait: 'جاهزة للاستلام',
    aucune_demande: 'لا توجد طلبات',
    aucun_utilisateur: 'لا يوجد مستخدمون',
    role_user: 'مواطن',
    role_admin: 'مسؤول',
    changer_role: 'تغيير الدور',
    aller_admin: 'فضاء الإدارة',
    retour_citoyen: 'عودة للمواطن',
  }
};

const LangContext = createContext();

export function LangProvider({ children }) {
  const [lang, setLang] = useState('fr');
  const t = (key) => translations[lang][key] || translations['fr'][key] || key;
  const isRTL = lang === 'ar';
  return (
    <LangContext.Provider value={{ lang, setLang, t, isRTL }}>
      <div dir={isRTL ? 'rtl' : 'ltr'} style={{ fontFamily: isRTL ? "'Scheherazade New', 'DM Sans', sans-serif" : "'DM Sans', sans-serif" }}>
        {children}
      </div>
    </LangContext.Provider>
  );
}

export function useLang() { return useContext(LangContext); }
